include: package:flutter_lints/flutter.yaml
linter:
  rules:

analyzer:
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.chopper.dart"
  errors:
    invalid_annotation_target: ignore