name: photo_gallery
description: Flutter Project Developed for Both IOS and Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  bloc: ^8.0.3

  authentication_repository:
    path: packages/authentication_repository

  form_inputs:
    path: packages/form_inputs

  photo_api:
    path: packages/photo_api

  firestore_photo_api:
    path: packages/firestore_photo_api

  formz: ^0.4.1
  equatable: ^2.0.3
  flow_builder: ^0.0.8

  #http for network calls
  http: ^0.13.4

  #flutter Bloc for architecture of the application
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.4

  google_fonts: ^2.3.2
  photo_view: ^0.13.0
  cached_network_image: ^3.2.0

  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.1

  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  image_picker: ^0.8.5+3

  uuid: ^3.0.6
  shimmer: ^2.0.0
  flutter_secure_storage: ^5.0.2
  injectable: ^1.5.3
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^3.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.10 # flutter pub run build_runner build --delete-conflicting-outputs
  freezed: ^2.0.2
  json_serializable: ^6.1.6


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  #generate: true

  assets:
    - assets/