name: photo_gallery
description: Flutter Project Developed for Both IOS and Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.16
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_mobx: ^2.0.6
  flutter_native_image: ^0.0.6+1
  font_awesome_flutter: ^10.1.0
  formz: ^0.4.1
  freezed_annotation: ^2.0.3
  mobx: ^2.0.7+2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+4
  json_annotation: ^4.5.0
  photo_view: ^0.13.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11 # flutter pub run build_runner build --delete-conflicting-outputs
  flutter_gen: ^4.1.6

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  mobx_codegen:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/
