name: firestore_photo_api
description: My new Firestore package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  firebase_auth: ^5.0.0
  cloud_firestore: ^3.1.15
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  photo_api:
    path: ../photo_api
  uuid: ^3.0.6

dev_dependencies:
  coverage: ^1.3.1
  mocktail: ^0.3.0
  test: ^1.21.1
  very_good_analysis: ^3.0.0