name: photo_api
description: The interface and models for an API providing access to photos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  meta: ^1.7.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  test: ^1.21.1
  very_good_analysis: ^6.0.0